// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjI6v4GO8XMnO1-Fz70hE6oyJPW2giX4c',
    appId: '1:740584871005:web:c6530611f7d2ab4d24e9b4',
    messagingSenderId: '740584871005',
    projectId: 'clinical-trials-9e16f',
    authDomain: 'clinical-trials-9e16f.firebaseapp.com',
    storageBucket: 'clinical-trials-9e16f.appspot.com',
    measurementId: 'G-3RC19R8WZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Aymw4yf9ulX-jJyXZJSGoNXqS3e1G3k',
    appId: '1:740584871005:android:76e7ed1bc48c440c24e9b4',
    messagingSenderId: '740584871005',
    projectId: 'clinical-trials-9e16f',
    storageBucket: 'clinical-trials-9e16f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBFix1AFQ8A5ijuwjSf1KqnTg7yhzm1D8',
    appId: '1:740584871005:ios:58ef285c8fd5546324e9b4',
    messagingSenderId: '740584871005',
    projectId: 'clinical-trials-9e16f',
    storageBucket: 'clinical-trials-9e16f.appspot.com',
    iosClientId: '740584871005-t56lrdn2lfromb4ovbfc0engq99ge167.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterJasmineTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBFix1AFQ8A5ijuwjSf1KqnTg7yhzm1D8',
    appId: '1:740584871005:ios:f27c6c6d527cc4c724e9b4',
    messagingSenderId: '740584871005',
    projectId: 'clinical-trials-9e16f',
    storageBucket: 'clinical-trials-9e16f.appspot.com',
    iosClientId: '740584871005-f1t09v95auf4brvuu3f34mp3tik1jqoh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterJasmineTest.RunnerTests',
  );
}
